plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'expo.modules.aethermotion'
version = '1.0.0'

android {
  namespace 'expo.modules.aethermotion'
  defaultConfig {
    versionCode 1
    versionName '1.0.0'
  }
  testOptions {
    unitTests.includeAndroidResources = false
    unitTests.returnDefaultValues = true
  }
}

dependencies {
  implementation 'com.github.Dimezis:BlurView:version-3.1.0'
  implementation 'androidx.metrics:metrics-performance:1.0.0'
  testImplementation 'junit:junit:4.13.2'
}
